// Wrangler integration: per-project config, local dev server, deploy, rollback.
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawn, execFileSync } from "node:child_process";
import { createServer } from "node:net";

const TOOL = join(dirname(fileURLToPath(import.meta.url)), "..");
const BIN = join(TOOL, "node_modules/wrangler/bin/wrangler.js");

export function writeConfig(p) {
  if (p.config.renderer === "astro") return writeStaticConfig(p);
  const routes = p.config.domain ? `routes = [${[].concat(p.config.domain).map((d) => `{ pattern = ${JSON.stringify(d)}, custom_domain = true }`).join(", ")}]\n` : "";
  mkdirSync(dirname(p.wrangler), { recursive: true });
  writeFileSync(p.wrangler, `# Generated by notionstatic from notionstatic.config.mjs; do not edit.
name = ${JSON.stringify(p.config.worker)}
main = ${JSON.stringify(join(TOOL, "worker/index.js"))}
compatibility_date = "2026-09-01"
${routes}
[assets]
directory = ${JSON.stringify(p.site)}
binding = "ASSETS"
run_worker_first = ["/api/*", "/image/*", "/_data/*", "/internal/*"]

[[rules]]
type = "Text"
globs = ["**/*.css", "**/*.inline.js"]
fallthrough = true
`);
  return p.wrangler;
}

// Astro output is plain static files: no Worker code, Cloudflare serves /About-x from About-x.html.
function writeStaticConfig(p) {
  const routes = p.config.domain ? `routes = [${[].concat(p.config.domain).map((d) => `{ pattern = ${JSON.stringify(d)}, custom_domain = true }`).join(", ")}]\n` : "";
  mkdirSync(dirname(p.wrangler), { recursive: true });
  writeFileSync(p.wrangler, `# Generated by notionstatic from notionstatic.config.mjs; do not edit.
name = ${JSON.stringify(p.config.worker)}
compatibility_date = "2026-09-01"
${routes}
[assets]
directory = ${JSON.stringify(p.dist)}
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
`);
  return p.wrangler;
}

export function wrangler(p, args, { capture = false } = {}) {
  writeConfig(p);
  const full = [BIN, ...args, "--config", p.wrangler];
  if (capture) return execFileSync(process.execPath, full, { cwd: p.dir, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  execFileSync(process.execPath, full, { cwd: p.dir, stdio: "inherit" });
}

export function whoami(p) {
  try { return /logged in/i.test(wrangler(p, ["whoami"], { capture: true })); } catch { return false; }
}

const freePort = () => new Promise((res) => { const s = createServer(); s.listen(0, () => { const { port } = s.address(); s.close(() => res(port)); }); });

// Start `wrangler dev`, resolve once it serves pages; returns { url, stop }.
export async function devServer(p, { port } = {}) {
  writeConfig(p);
  port ||= await freePort();
  const child = spawn(process.execPath, [BIN, "dev", "--config", p.wrangler, "--port", String(port), "--log-level", "warn"], { cwd: p.dir, stdio: ["ignore", "pipe", "pipe"] });
  let out = "";
  child.stdout.on("data", (d) => (out += d)); child.stderr.on("data", (d) => (out += d));
  const url = `http://localhost:${port}`;
  const stop = () => new Promise((r) => { if (child.exitCode != null) return r(); child.once("exit", r); child.kill("SIGTERM"); setTimeout(() => child.kill("SIGKILL"), 5000); });
  for (let i = 0; i < 120; i++) {
    if (child.exitCode != null) throw new Error(`wrangler dev exited:\n${out.slice(-1500)}`);
    try { const r = await fetch(url + "/"); if (r.status < 500) return { url, stop, child }; } catch {}
    await new Promise((r) => setTimeout(r, 500));
  }
  await stop();
  throw new Error(`wrangler dev did not start:\n${out.slice(-1500)}`);
}
